name: proxy container build

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v2
        with:
          version: latest
      - name: make images
        run: make
      - name: check images
        run: |
          docker images
          # | grep 'grantmacken'
          # make run
          # make stop
      # - name: Push to Dockerhub and Github Packages
        # run: |
          # source .env
          # echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${REPO_OWNER} --password-stdin 
          # docker push ${DOCKER_IMAGE}:${NGINX_VER}
          # echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ${REPO_OWNER} --password-stdin
          # docker push docker.pkg.github.com/${REPO_OWNER}/${REPO_NAME}/${PROXY_CONTAINER_NAME}:${PROXY_VER}
